---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-simonlab-xyz-argocd
  namespace: argocd
spec:
  secretName: local-simonlab-xyz-argocd-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.simonlab.xyz"
  dnsNames:
  - "local.simonlab.xyz"
  - "*.local.simonlab.xyz"